
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800 border-bottom">Agregar Fincas</h1>
        
        <form action="" method="post" class="form">
            <input type="hidden" name="add" value="1">

            <div class="form-group"><label for="nombre">Nombre</label><input type="text" name="nombre" id="nombre" class="form-control" placeholder="nombre"></div>
            <div class="form-group"><label for="description">Propietario</label><input type="text" name="propietario" id="propietario" class="form-control" placeholder="Propietario"></div>
            <div class="form-group"><label for="precio">Dirección</label><input type="text" name="direccion" id="direccion" class="form-control" placeholder="Direccion"></div>
            <input type="submit" value="Agregar" class="btn btn-primary">
            
        </form>