    <div class="modal fade" id="modalEditar">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title font-weight-normal">Actualizar Productos</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="formEdit" method="post" class="form" >
                <input type="hidden" name="editar" value="1">
                <div class="card-body">

                  <input type="hidden" class="form-control" id="id" name="id">

                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Nombre:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="nombre" name="nombre">
                    </div>
                  </div>

                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">PROPIETARIO:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="propietario" name="propietario">
                    </div>
                  </div>
                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">direction: :</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="direccion" name="direccion">
                    </div>
                  </div>

                  
                </div>
            </div>
            <div class="modal-footer justify-content-between table">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>

      
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800 border-bottom">Fincas</h1>
          <p class="mb-4 d-flex justify-content-end">
            <a href="<?= BASE_URL ?>productos/add" class="btn btn-secondary btn-icon-split">
              <span class="icon text-white-50">
                <i class="fas fa-file"></i>
              </span>
              <span class="text">Agregar Fincas</span>
            </a>
          </p>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <?= $this->titulo ?>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered text-center " id="tabla" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>NOMBRE</th>
                      <th>PROPIETARIO</th>
                      <th>DIRECCION</th>
                      <th colspan="2">ACCIONES</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?= $this->contenido ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>


           <!-- Logout Modal-->
  